# Generated by Django 3.0.5 on 2020-04-25 22:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(default='00000', max_length=20)),
                ('physical_address', models.CharField(default='NA', max_length=100)),
                ('name', models.CharField(default='NA', max_length=30)),
                ('timetable', jsonfield.fields.JSONField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
