# Generated by Django 3.0.5 on 2020-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='besttime',
            field=models.CharField(default='8:00am', max_length=10),
        ),
    ]
