# Generated by Django 3.0.5 on 2020-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200425_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(default='0.000000', max_length=15),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.CharField(default='0.000000', max_length=15),
        ),
    ]
